name: Yor Action Testing
on:
  push:
    branches:
      - master


jobs:
  yor-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
        with:
          commit_changes: NO # Any value which is not YES (which is the default value) will lead to no commit